In [1]:
## helpful packages
import pandas as pd
import numpy as np
import random
import re
import os

## repeated printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


# Now we work on loading and inspecting the data sets

In [4]:
import pickle
import pandas as pd

# File path
file_path = '/Users/alexwitheiler/Downloads/covid_sample-0.001.pkl'

data = pd.read_pickle(file_path)

# Now we can work with 'data' DataFrame
data.head

<bound method NDFrame.head of                     tweetid               userid    screen_name  \
15605   1220641644367765504   747463650881970176   gareth_grier
16910   1220640235358281729   937270922234363905      Rose_ifnt
8796    1220632931489574913           3869545214     SinoVoices
14795   1220642433127436288           1053953342  _KhairiHassan
4225    1220640550178762753  1104714610421190656    Gaz60656269
...                     ...                  ...            ...
90900   1482664673854038016            508859323      laudemare
22201   1482656524245909507  1390529577760530433     Justbob111
81791   1482663571716775936  1464936163123281923     falcon2800
88826   1482664418727145473            798161712    KevinSalvat
102639  1482666092438953995  1327585064541106177   claveledith1

                                  date lang       location place_id place_url  \
15605   Fri Jan 24 09:37:01 +0000 2020   en            NaN      NaN       NaN
16910   Fri Jan 24 09:31:25 +0000 2020   en            NaN      NaN       NaN
8796    Fri Jan 24 09:02:23 +0000 2020   en            NaN      NaN       NaN
14795   Fri Jan 24 09:40:09 +0000 2020   en            NaN      NaN       NaN
4225    Fri Jan 24 09:32:40 +0000 2020   en            NaN      NaN       NaN
...                                ...  ...            ...      ...       ...
90900   Sun Jan 16 10:42:59 +0000 2022   fr            NaN      NaN       NaN
22201   Sun Jan 16 10:10:36 +0000 2022   en  Great Britain      NaN       NaN
81791   Sun Jan 16 10:38:36 +0000 2022   pt            NaN      NaN       NaN
88826   Sun Jan 16 10:41:58 +0000 2022   en         Surrey      NaN       NaN
102639  Sun Jan 16 10:48:37 +0000 2022   fr            NaN      NaN       NaN

       place_type place_name  ...      rt_country qtd_state qtd_country  \
15605         NaN        NaN  ...             NaN       NaN         NaN
16910         NaN        NaN  ...     Switzerland       NaN         NaN
8796          NaN        NaN  ...             NaN       NaN         NaN
14795         NaN        NaN  ...             NaN       NaN         NaN
4225          NaN        NaN  ...  United Kingdom       NaN         NaN
...           ...        ...  ...             ...       ...         ...
90900         NaN        NaN  ...             NaN       NaN         NaN
22201         NaN        NaN  ...             NaN       NaN         NaN
81791         NaN        NaN  ...             NaN       NaN         NaN
88826         NaN        NaN  ...             NaN       NaN         NaN
102639        NaN        NaN  ...             NaN       NaN         NaN

          norm_country norm_rt_country norm_qtd_country  \
15605              NaN             NaN              NaN
16910              NaN     Switzerland              NaN
8796               NaN             NaN              NaN
14795              NaN             NaN              NaN
4225               NaN  United Kingdom              NaN
...                ...             ...              ...
90900              NaN             NaN              NaN
22201   United Kingdom             NaN              NaN
81791              NaN             NaN              NaN
88826   United Kingdom             NaN              NaN
102639             NaN             NaN              NaN

                                              description  \
15605                                                 NaN
16910                                                 NaN
8796                                                  NaN
14795                                                 NaN
4225                                                  NaN
...                                                   ...
90900                                                 NaN
22201   ex trawlerman, ex forces, now C&I engineer \n\...
81791                                               Hmmâ€¦ðŸ¤”
88826                                                 NaN
102639  Â«Â Dans la vie on ne fait pas ce que lâ€™on veut ...

                                      rt_user_description  \
15605                                                 NaN
16910                                                 NaN
8796                                                  NaN
14795                                                 NaN
4225                                                  NaN
...                                                   ...
90900   Compte officiel. Chaque dimanche Ã  18h en excl...
22201                                                 NaN
81791                                                 NaN
88826   Cofounder of @joinlincoln + new co. alum: grow...
102639                                                NaN

                                     qtd_user_description  acc_age
15605                                                 NaN      NaN
16910                                                 NaN      NaN
8796                                                  NaN      NaN
14795                                                 NaN      NaN
4225                                                  NaN      NaN
...                                                   ...      ...
90900                                                 NaN   3608.0
22201                                                 NaN    254.0
81791   É±Ïƒâˆ‚Îµâ„“\nâˆ‚à¹€ÎµÉ¦Î±É¾âˆ‚ Æ’Î±É³ÏƒÆ’_\nà¸£É¦Î±É¦É¾ÂµÒ¡É¦Ò¡É¦Î±É³ ,\nÒ¡à¹€Î±É¾Î± Î±...     48.0
88826                                                 NaN   3422.0
102639                                                NaN    427.0

[1899693 rows x 76 columns]>

In [ ]:
import pandas as pd

# Path to the file
file_path = '/Users/amanda/Downloads/tweets_list.pkl'

# Load the data from the pickle file
data = pd.read_pickle(file_path)

# Display the first few rows of the dataframe
data

columns = ['username', 'location', 'description', 'followers', 'verified', 'tweet', 'datetime', 'extra_column']
df = pd.DataFrame(data, columns=columns)

# Handle missing values or extra columns
df.drop(columns=['extra_column'], inplace=True)  # Remove if not needed
df.fillna('Missing')  # Fill missing data